### ISSUE TITLE
Error with word ended with -y

### ISSUE THREAD

**Issue by lemonnm** [joshualat/Pluralize.swift#1]
I try the project with "City".pluralize() and "Amnesty".pluralize()

Result : "Citys" and "Amnestys"
Good result : "Cities" and "Amnesties"

I think this rule is not good :

``` swift
rule("(r|l|b)y$", with:"$1ies")
```

Thx,

**Comment by joshualat** [comment]
Hi Lemonnier!

Thank you for reporting this bug. 

Commit https://github.com/joshualat/Pluralize.swift/commit/8f2926df5c319f5245d09ff99d36da15b1262158 should fix the bug.

_Before:_

```
rule("(r|l|b)y$", with:"$1ies")
```

_After:_

```
rule("(t|r|l|b)y$", with:"$1ies")
```

Hope this helps!

Josh
